require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BartendersController do

  # This should return the minimal set of attributes required to create a valid
  # Bartender. As you add validations to Bartender, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "bar" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BartendersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all bartenders as @bartenders" do
      bartender = Bartender.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bartenders).should eq([bartender])
    end
  end

  describe "GET show" do
    it "assigns the requested bartender as @bartender" do
      bartender = Bartender.create! valid_attributes
      get :show, {:id => bartender.to_param}, valid_session
      assigns(:bartender).should eq(bartender)
    end
  end

  describe "GET new" do
    it "assigns a new bartender as @bartender" do
      get :new, {}, valid_session
      assigns(:bartender).should be_a_new(Bartender)
    end
  end

  describe "GET edit" do
    it "assigns the requested bartender as @bartender" do
      bartender = Bartender.create! valid_attributes
      get :edit, {:id => bartender.to_param}, valid_session
      assigns(:bartender).should eq(bartender)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bartender" do
        expect {
          post :create, {:bartender => valid_attributes}, valid_session
        }.to change(Bartender, :count).by(1)
      end

      it "assigns a newly created bartender as @bartender" do
        post :create, {:bartender => valid_attributes}, valid_session
        assigns(:bartender).should be_a(Bartender)
        assigns(:bartender).should be_persisted
      end

      it "redirects to the created bartender" do
        post :create, {:bartender => valid_attributes}, valid_session
        response.should redirect_to(Bartender.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bartender as @bartender" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bartender.any_instance.stub(:save).and_return(false)
        post :create, {:bartender => { "bar" => "invalid value" }}, valid_session
        assigns(:bartender).should be_a_new(Bartender)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bartender.any_instance.stub(:save).and_return(false)
        post :create, {:bartender => { "bar" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bartender" do
        bartender = Bartender.create! valid_attributes
        # Assuming there are no other bartenders in the database, this
        # specifies that the Bartender created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bartender.any_instance.should_receive(:update).with({ "bar" => "MyString" })
        put :update, {:id => bartender.to_param, :bartender => { "bar" => "MyString" }}, valid_session
      end

      it "assigns the requested bartender as @bartender" do
        bartender = Bartender.create! valid_attributes
        put :update, {:id => bartender.to_param, :bartender => valid_attributes}, valid_session
        assigns(:bartender).should eq(bartender)
      end

      it "redirects to the bartender" do
        bartender = Bartender.create! valid_attributes
        put :update, {:id => bartender.to_param, :bartender => valid_attributes}, valid_session
        response.should redirect_to(bartender)
      end
    end

    describe "with invalid params" do
      it "assigns the bartender as @bartender" do
        bartender = Bartender.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bartender.any_instance.stub(:save).and_return(false)
        put :update, {:id => bartender.to_param, :bartender => { "bar" => "invalid value" }}, valid_session
        assigns(:bartender).should eq(bartender)
      end

      it "re-renders the 'edit' template" do
        bartender = Bartender.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bartender.any_instance.stub(:save).and_return(false)
        put :update, {:id => bartender.to_param, :bartender => { "bar" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bartender" do
      bartender = Bartender.create! valid_attributes
      expect {
        delete :destroy, {:id => bartender.to_param}, valid_session
      }.to change(Bartender, :count).by(-1)
    end

    it "redirects to the bartenders list" do
      bartender = Bartender.create! valid_attributes
      delete :destroy, {:id => bartender.to_param}, valid_session
      response.should redirect_to(bartenders_url)
    end
  end

end
